[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
via_ir = true
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]

# Package information
name = "defi-and-dragons"
version = "0.1.0"
description = "A fantasy RPG framework for DeFi interactions"
license = "MIT"
homepage = "https://github.com/lcanady/defi-and-dragons"
repository = "https://github.com/lcanady/defi-and-dragons"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
